name: sf_pampanga_terminals
description: SF Pampanga Terminals App
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3
  dio_http2_adapter: ^2.1.0
  google_fonts: ^6.2.1


  http: ^1.2.2
  app_settings: ^5.1.1

  # Firebase
  firebase_core: ^2.27.1
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.7
  image_picker: ^1.0.7
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.2
  firebase_app_check: 0.2.2+7

  # Location
  geolocator: ^11.0.0
  permission_handler: ^11.3.1

  # Map
  maplibre_gl: ^0.23.0
  flutter_compass: ^0.8.0

  # Utils
  uuid: ^4.5.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/jeep_icon.png
    - assets/bus_icon.png
    - assets/cluster_icon.png
    - assets/red_marker.png
    - assets/gps_pointer.png

    # --- Paths for your icon and splash ---
    - assets/icon/
    - assets/splash/

# --- Configuration for App Icon ---
# Make sure to put your round app icon at 'assets/icon/app_icon.png'
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

# --- Configuration for Splash Screen ---
# Make sure to put your splash screen logo at 'assets/splash/splash_logo.png'
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/splash/splash_logo.png"
  color_dark: "#FFFFFF" # Using white background for dark mode too
  image_dark: "assets/splash/splash_logo.png"

  android_12:
    color: "#FFFFFF"
    image: "assets/splash/splash_logo.png"
    color_dark: "#FFFFFF"
    image_dark: "assets/splash/splash_logo.png"
